server:
  port: 8080

spring:
  application:
    name: erp

  datasource:
    url: jdbc:mysql://localhost:3306/erpdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG               # SQL 쿼리 출력
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # 바인딩 값 출력
    org.springframework.jdbc: debug
    org.mybatis: DEBUG

mybatis:
#  매핑될 xml 파일은 이 결로 밑에 있으면 스캔대상
  mapper-locations: classpath:mapper/**/*.xml
#  xml 파일에서 사용될 객체 이 경로 아래 있으면 스캔대상
  type-aliases-package: com.sunmight.erp.domain
#  카멜 케이스로 세팅됨
  configuration:
    map-underscore-to-camel-case: true